### ISSUE TITLE
ImportError: No module named configparser

### ISSUE THREAD

**Issue by omegarus** [blacked/py-zabbix#24]
I installed py-zabbix with pip.
What i'm doing wrong ?
```
root@host1:/tmp# pip --version
pip 1.5.4 from /usr/lib/python2.7/dist-packages (python 2.7)
root@host1:/tmp# python
Python 2.7.6 (default, Jun 22 2015, 17:58:13)
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from zabbix.sender import ZabbixMetric
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/zabbix/sender.py", line 1, in <module>
    import configparser
ImportError: No module named configparser
>>>
```

**Comment by mikkabond** [comment]
You are doing rigth))) It is just a bug. zabbix/sender.py (in python distribution directory) delete "import configparser" and add folowing code:
```
try:
    import ConfigParser
except ImportError:
    import configparser
```
after 
"""
Python3 compatibility
"""

**Comment by blacked** [comment]
That but actually was fixed a long time ago, but i forgot update pip version, so if you will install from github, you will never get this issue. I will update pip package also.

**Comment by blacked** [comment]
done.
